from django.test import TestCase
from django.urls import reverse
from rest_framework import status

from engine.service import convert_sql, UnsupportedStatementTypeError
from engine.translators.ddl_translator import convert_ddl
from .models import ConversionJob


class EngineDDLTests(TestCase):
    def test_tsql_to_postgres_ddl(self):
        result = convert_ddl(
            """CREATE TABLE Employees (
                EmployeeID INT IDENTITY(1,1) PRIMARY KEY,
                Salary MONEY,
                IsActive BIT DEFAULT 1,
                EmployeeGuid UNIQUEIDENTIFIER DEFAULT NEWID()
            );""",
            source_dialect="tsql",
            target_dialect="postgres",
        )
        self.assertTrue(result.sql)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", result.sql)
        self.assertIn("NUMERIC(19,4)", result.sql)
        self.assertIn("BOOLEAN DEFAULT true", result.sql)
        self.assertIn("UUID", result.sql)

    def test_postgres_to_tsql_ddl(self):
        result = convert_ddl(
            """CREATE TABLE Employees (
                EmployeeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                IsActive BOOLEAN DEFAULT true
            );""",
            source_dialect="postgres",
            target_dialect="tsql",
        )
        self.assertTrue(result.sql)
        self.assertIn("IDENTITY(1, 1)", result.sql)
        self.assertIn("BIT DEFAULT 1", result.sql)
        self.assertNotIn("1 = 1", result.sql)

    def test_manual_review_type_flagged(self):
        result = convert_ddl(
            "CREATE TABLE Locations (LocationID INT PRIMARY KEY, Notes SQL_VARIANT);",
            source_dialect="tsql",
            target_dialect="postgres",
        )
        self.assertTrue(any("MANUAL REVIEW REQUIRED" in w for w in result.warnings))

    def test_postgres_to_tsql_strips_pg_casts_from_defaults(self):
        result = convert_ddl(
            """CREATE TABLE Orders (
                OrderID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                Status VARCHAR(20) DEFAULT 'Pending'::character varying,
                CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );""",
            source_dialect="postgres",
            target_dialect="tsql",
        )
        self.assertTrue(result.sql)
        self.assertIn("DEFAULT 'Pending'", result.sql)
        self.assertNotIn("::", result.sql)
        self.assertIn("DEFAULT GETDATE()", result.sql)

    def test_postgres_to_tsql_computed_column_has_no_type(self):
        result = convert_ddl(
            """CREATE TABLE OrderItems (
                OrderItemID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                Quantity INT NOT NULL,
                UnitPrice NUMERIC(19,4) NOT NULL,
                LineTotal NUMERIC(19,4) GENERATED ALWAYS AS ((Quantity)::numeric * UnitPrice) STORED
            );""",
            source_dialect="postgres",
            target_dialect="tsql",
        )
        self.assertTrue(result.sql)
        self.assertNotIn("::", result.sql)
        col_def = result.sql[result.sql.index("LineTotal"):result.sql.index("Quantity")]
        self.assertNotIn("NUMERIC", col_def)


class EngineServiceTests(TestCase):
    def test_dml_routed_through_facade(self):
        result = convert_sql(
            "SELECT TOP 5 EmployeeID FROM Employees ORDER BY EmployeeID;",
            direction="mssql_to_postgres",
            statement_type="dml",
        )
        self.assertIn("LIMIT 5", result.sql)
        self.assertIn("ORDER BY", result.sql)

    def test_unsupported_statement_type_raises(self):
        with self.assertRaises(UnsupportedStatementTypeError):
            convert_sql(
                "CREATE PROCEDURE P AS BEGIN SELECT 1; END;",
                direction="mssql_to_postgres",
                statement_type="procedure",
            )


class ConvertAPITests(TestCase):
    def _convert(self, payload):
        return self.client.post(reverse("api-convert"), payload, content_type="application/json")

    def test_convert_ddl_success(self):
        response = self._convert({
            "source_sql": "CREATE TABLE t (id INT IDENTITY(1,1) PRIMARY KEY, active BIT DEFAULT 1);",
            "direction": "mssql_to_postgres",
            "statement_type": "ddl",
        })
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        body = response.json()
        self.assertTrue(body["succeeded"])
        self.assertIn("BOOLEAN DEFAULT true", body["converted_sql"])
        self.assertTrue(ConversionJob.objects.filter(pk=body["id"]).exists())

    def test_convert_dml_success(self):
        response = self._convert({
            "source_sql": "SELECT TOP 3 * FROM t;",
            "direction": "mssql_to_postgres",
            "statement_type": "dml",
        })
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.json()["succeeded"])

    def test_unsupported_statement_type_returns_501(self):
        response = self._convert({
            "source_sql": "CREATE PROCEDURE P AS BEGIN SELECT 1; END;",
            "direction": "mssql_to_postgres",
            "statement_type": "procedure",
        })
        self.assertEqual(response.status_code, status.HTTP_501_NOT_IMPLEMENTED)
        self.assertFalse(response.json()["succeeded"])
        self.assertIn("isn't implemented yet", response.json()["error_message"])

    def test_reverse_direction_works(self):
        response = self._convert({
            "source_sql": "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, active BOOLEAN DEFAULT true);",
            "direction": "postgres_to_mssql",
            "statement_type": "ddl",
        })
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("BIT DEFAULT 1", response.json()["converted_sql"])
