# Generated by Django 6.1 on 2026-08-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('mssql_to_postgres', 'SQL Server → PostgreSQL'), ('postgres_to_mssql', 'PostgreSQL → SQL Server')], max_length=32)),
                ('statement_type', models.CharField(choices=[('ddl', 'DDL (CREATE TABLE, etc.)'), ('dml', 'DML (SELECT/INSERT/UPDATE/DELETE)'), ('procedure', 'Stored Procedure / Function'), ('trigger', 'Trigger')], default='ddl', max_length=16)),
                ('source_sql', models.TextField()),
                ('converted_sql', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
