# Generated by Django 6.1 on 2026-08-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_databaseconnection_migrationjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='reset_target',
            field=models.BooleanField(default=False, help_text='Drop target schemas being migrated into before running (destructive to prior runs).'),
        ),
    ]
