# Generated by Django 6.1 on 2026-08-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_migrationjob_reset_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_kind', models.CharField(choices=[('table', 'Table'), ('index', 'Index'), ('constraint', 'Constraint'), ('view', 'View'), ('function', 'Function'), ('procedure', 'Procedure'), ('trigger', 'Trigger'), ('data', 'Data copy'), ('object', 'Object')], default='object', max_length=16)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('error_type', models.CharField(blank=True, default='sql_error', max_length=64)),
                ('message', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True, help_text='Failing statement / extra context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='converter.migrationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
